apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: web-gw
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-http-route
spec:
  parentRefs:
    - name: my-gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: my-service
          port: 80

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: cilium-gateway

# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: Gateway
# metadata:
#   name: home-gateway
#   # namespace: cilium-gateway
#   # labels:
#   #   app: home-gateway
#   #   env: gateway
# spec:
#   gatewayClassName: cilium
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 80
#     allowedRoutes:
#       namespaces:
#         from: All
# # ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: home-http-route
#   namespace: cilium-gateway
#   labels:
#     app: home-http-route
#     env: external
# spec:
#   parentRefs:
#   - name: home-gateway
#     namespace: cilium-gateway
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /
#     backendRefs:
#     - name: stirling-pdf
#       namespace: stirling-pdf
#       port: 8080