apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: home-gateway
  namespace: cilium-gateway
  labels:
    app: home-gateway
    env: external
spec:
  gatewayClassName: cilium-gateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    