ipam:
  mode: "kubernetes"
kubeProxyReplacement: true
# kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"
securityContext:
  capabilities:
    ciliumAgent:
      - NET_BIND_SERVICE
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
l2announcements:
  enabled: true
externalIPs:
  enabled: true
k8sClientRateLimit:
  qps: 20
  burst: 200
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled: 
    - dns
    - droptcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction


    enableOpenMetrics: true
    serviceMonitor:
      enabled: true 
    dashboards:
      enabled: true
      label: grafana_dashboard
      namespace: monitoring
gatewayAPI:
  enabled: true
  enableAppProtocol: true
  enableAlpn: true
  hostNetwork:
    enabled: true
envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
operator:
  replicas: 1
# envoyConfig:
#   enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
ingressController:
  enabled: false
#   enforceHttps: false
