# vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: resume-db-owner
  namespace: cnpg-cluster
spec:
  # Authentication reference
  vaultAuthRef: cnpg-cluster/cluster-vault-auth

  # Vault path (KV v2)
  mount: dbusers
  type: kv-v1
  path: data/resume/owner

  # Kubernetes Secret to create
  destination:
    name: resume-db-owner
 #   namespace: resume
    create: true

  # Refresh interval
  refreshAfter: 1h

  # Rollout restart annotations
#  rolloutRestartTargets:
#  - kind: Deployment
#    name: myapp
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: resume-db-owner
  namespace: cnpg-cluster
spec:
  cluster:
    name: cnpg-cluster
  name: reactive_resume
  comment: "Owner role for resume DB"
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: delete
  inRoles:
    - pg_monitor
  passwordSecret:
    name: resume-db-owner
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: resume-db
spec:
  name: resume-db
  owner: reactive_resume
  cluster:
    name: cnpg-cluster
  extensions:
    - name: bloom
      ensure: present
