apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: test-pool
spec:
  blocks:
  - start: "10.50.0.240"
    stop: "10.50.0.250"
  serviceSelector:
    matchExpressions:
      - {key: env, operator: In, values: [test, experiment]}