apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      targetRevision: 1.20.2
      path: .
      
      
  destination:
    server: https://kubernetes.default.svc
    namespace: certmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true