apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi
  namespace: argocd
spec:
  project: default
  sources:
             
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      path: nfs-csi
      
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs_csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
