apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shaarli
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      path: Shaarli
      
  destination:
    server: https://kubernetes.default.svc
    namespace: shaarli
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true