apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
      chart: stirling-pdf-chart
      targetRevision: 3.1.0
      helm:
        valueFiles:
          - $values/Stirling_helm/values.yaml
          
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      path: Stirling_helm  
    # - repoURL: https://github.com/huntrrose/gitops.git
    #   targetRevision: HEAD
    #   path: Stirling
      
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
