apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifios
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://rubxkube.github.io/charts/
      chart: stirling-pdf
      targetRevision: 0.0.9
      helm:
        valueFiles:
          - $values/unifiHelm/values.yaml
          
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      path: unifiHelm  
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
