apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
spec:
  project: default
  sources:    
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      path: Unifi
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
