apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://chrissnell.github.io/unifi-os-kubernetes
      chart: unifi-os/unifi-os-server
      targetRevision: 0.2.3
      helm:
        valueFiles:
          - $values/unifiHelm/values.yaml     
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/huntrrose/gitops.git
      targetRevision: HEAD
      path: unifiHelm  
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
