apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-csi-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-csi-test
  template:
    metadata:
      labels:
        app: nfs-csi-test
    spec:
      containers:
        - name: nfs-csi-test
          image: alpine:latest
          
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nfs-csi-test-secret
  namespace: default
spec:
  vaultAuthRef: nfs-csi-test-auth
  type: kv-v2
  mount: kv-v2
  path: k8s/testSecret
  refreshAfter: 60s
  destination:
    name: nfs-csi-test-secret-creds
    create: true
  rolloutRestartTargets:
  - kind: Deployment
    name: nfs-csi-test
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: nfs-csi-test-auth
  namespace: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: test
    serviceAccount: default
    #tokenExpirationSeconds: 600
    audiences: 
      - vault