alertmanager:
  alertmanagerspec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-server
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
prometheus:
  prometheusspec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-server
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi

prometheus-node-exporter:
  podSecurityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

kubeEtcd:
  endpoints: 
    - 10.50.0.20

grafana:
  # service:
  #   type: ClusterIP
  #   labels:
  #     env: internal
  persistence:
    enabled: true
    storageClassName: nfs-server
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  adminUser: admin
  adminPassword: TempPass123!