# vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cluster-vault-auth
  namespace: cnpg-system
spec:
  # Reference to VaultConnection
  vaultConnectionRef: vault-secrets-operator/default

  # Authentication method
  method: kubernetes

  # Mount path for auth method
  mount: kubernetes

  # Kubernetes auth configuration
  kubernetes:
    role: cnpg_cluster
    serviceAccount: default
