cluster:
  storage:
    size: 10Gi
    storageClass: local-path
  monitoring:
    enabled: true
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: true
#  roles: 
#    - name: ncdb 
#      ensure: present
#      comment: NextCloud DB User
#      login: true
#      superuser: false
#      passwordSecret:
#        name: 
