apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pvc
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  # storageClassName: nfs-server