---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shaarli-pvc
  namespace: shaarli
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaarli
  namespace: shaarli
  labels:
    app: shaarli
    env: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shaarli
  template:
    metadata:
      labels:
        app: shaarli
    spec:
      containers:
      - name: shaarli
        image:  ghcr.io/shaarli/shaarli:latest
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop: ["ALL"]
        #   seccompProfile:
        #     type: RuntimeDefault
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   runAsGroup: 1000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: shaarli-data
            mountPath: /var/www/shaarli/data
            subPath: shaarli-data
          - name: shaarli-data
            mountPath: /var/www/shaarli/cache
            subPath: shaarli-cache
      volumes:
        - name: shaarli-data
          persistentVolumeClaim:
            claimName: shaarli-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: shaarli
  namespace: shaarli
spec: 
  selector:
    app: shaarli
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  type: ClusterIP
---  
apiVersion: networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shaarli
  namespace: shaarli
spec:
  parentRefs:
    - name: gw-external
      namespace: gateway
      sectionName: shaarli-http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      defaultBackendRefs:
        - name: shaarli
          namespace: shaarli
          port: 80
  