apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: resume-db-creds
  namespace: resume
spec:
  vaultAuthRef: resume-vault-auth

  mount: cnpg-cluster
  path: resumedb/resume_db_user

  destination:
    name: resume-db-secret
    create: true

  renewalPercent: 67

  revoke: true

  refreshAfter: 24h

  rolloutRestartTargets:
    - kind: Deployment
      name: reactive-resume

