apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: resume-listeners
  namespace: resume
  labels:
    env: internal
spec:
  parentRef:
    name: gw-internal
    namespace: gateway
#    kind: Gateway
#    group: gateway.networking.k8s.io
  listeners:
    - name: resume-http
      hostname: resume.huntrrose.local
      protocol: HTTP
      port: 80
