apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: resume-listeners
  namespace: resume
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-parentreffallback: "true"
  labels:
    access: external 
spec:
  parentRef:
    name: gw-external
    namespace: gateway
#    kind: Gateway
#    group: gateway.networking.k8s.io
  listeners:
    - name: resume-https
      hostname: resume.huntrrose.com
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: resume-cert
