apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-storage
  namespace: resume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
      # storageclass: longhorn #Default
