apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-storage
  namespace: resume
spec:
  accessModes:
    - ReadWriteOnce
  resource:
    storage: 2Gi
    # storageclass: longhorn #Default
