common:
  service:
      enabled: true
  variables:
    nonSecret:
      DOCKER_ENABLE_SECURITY: false
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
      LANGS: en_GB
  persistence:
    enabled: true
    
    volumes:
      - name: "trainingdata"
        storageClassName: longhorn
        size: "10Gi"
        pvcClaim: ""
        containerMount: "/usr/share/tessdata"
      - name: "config"
        storageClassName: longhorn
        size: "1Gi"
        pvcClaim: ""
        containerMount: "/configs"
      - name: "log"
        storageClassName: longhorn
        size: "1Gi"
        pvcClaim: ""
        containerMount: "/logs"
      - name: "pdfdata"
        storageClassName: longhorn
        size: "1Gi"
        pvcClaim: ""
        containerMount: "/tmp"
  ingress:
    enabled: false