# deployment:
#   extraVolumes: 
#     - name: stirling-pvc
#       persistentVolumeClaim:
#         claimName: stirling-pvc
#   extraVolumeMounts:
#     - name: stirling-pvc
#       mountPath: /usr/share/tessdata
#       subPath: tessdata
#     - name: stirling-pvc
#       mountPath: /configs
#       subPath: configs
#     - name: stirling-pvc
#       mountPath: /logs
#       subPath: logs
#     - name: stirling-pvc
#       mountPath: /pipeline
#       subPath: pipeline 

service:
  type: LoadBalancer
  labels: 
    env: home
serviceMonitor:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 100Mi
  requests:
    cpu: 80m
    memory: 64Mi

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 1Gi
  storageClass: nfs-server
  path: /tmp