apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: role-nextcloud
  namespace: cnpg-system 
spec:
  cluster:
    name: cnpg-cluster
  name: ncdb 
#    valueFrom:
#      secretKeyRef:
#        name: nc-db-secret
#        kdey: username
  comment: "Nextcloud user"
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: delete
  inRoles:
    - pg_monitor
  passwordSecret:
    name: nc-db-user
#    namespace: nextcloud
#    ke: password
#
