apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  parentRefs:
    - name: gw-internal
      namespace: gateway
      sectionName: web-gw
  hostnames:
    - argocd.huntrrose.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    SbackendRefs:
      - name: argocd-server
        namespace: argocd
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-listener-int
      kind: ListenerSet
      sectionName: https
  hostnames:
    - argocd.huntrrose.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    - backendRefs:
      - name: argocd-server
        namespace: argocd
        kind: Service
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https-dummy
  namespace: argocd
spec:
  parentRefs:
    - name: argocd-listener
      kind: ListenerSet
      sectionName: https
  hostnames:
    - argocd.huntrrose.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
#    - backendRefs:
#      - name: argocd-server
#        namespace: argocd
#        port: 443
