---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: argocd-listener
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    name: gw-external
    namespace: gateway
  listeners:
    - name: https
      hostname: argocd.huntrrose.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: argo-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: argocd-listener-int
  namespace: argocd
spec:
  parentRef:
    name: gw-internal
    namespace: gateway
  listeners:
    - name: https
      hostname: argocd.huntrrose.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: argo-cert
