apiVersion: v1
kind: Namespace
metadata:
  name: linkding
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
    env: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
    container:
      - name: linkding
        image: sissbruecker/linkding:latest
        ports:
          - containerPort: 8000
        env:
          - name: LINKDING__DATABASE__CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: linkding-secrets
                key: connection-string