apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.32.0
      helm:
        values: |
          server:
            dataStorage:
              enabled: true
              existingClaim: vault-data-pvc
            auditStorage:
              enabled: true
              existingClaim: vault-audit-pvc
    - repoURL: https://github.com/huntrrose/gitops.git
      path: Vault
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
