server:
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: nfs-server
  auditStorage:
    enabled: true
    size: 1Gi
    storageClass: nfs-server

  volumes:
    - name: vault-data
      persistentVolumeClaim:
        claimName: vault-data-pvc
    - name: vault-audit
      persistentVolumeClaim:
        claimName: vault-audit-pvc
  volumeMounts:
    - name: vault-data
      mountPath: /vault/data
    - name: vault-audit
      mountPath: /vault/audit