apiVersion: v1
kind: Namespace
metadata:
  name: unifi
  labels:
    # Essentially disables PodSecurity for this namespace
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-db
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-db
  template:
    metadata:
      labels:
        app: unifi-db
    spec:
      containers:
      - name: unifi-db  
        image: docker.io/mongo:8.2.7
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: unifi-mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unifi-mongo-creds
              key: password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: unifi-mongo-creds
              key: username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: unifi-mongo-creds
              key: password
        - name: MONGO_DB
          value: unifi
        - name: MONGO_AUTHSOURCE
          value: admin
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: unifi-db-data
          mountPath: /data/db
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          #fsGroup: 999
      volumes:
      - name: unifi-db-data
        persistentVolumeClaim:
          claimName: unifidb-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
        image: lscr.io/linuxserver/unifi-network-application:latest
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: MONGO_HOST
          value: unifi-db.unifi.svc.cluster.local
        - name: MONGO_PORT
          value: 27017
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: unifi-mongo-creds
              key: username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: unifi-mongo-creds
              key: password
        - name: MONGO_DB
          value: unifi
        - name: MONGO_AUTHSOURCE
          value: unifi
        - name: TZ
          value: "Etc/UTC"
        #- name: PUID
        #  value: "999"
        #- name: PGID
        #  value: "999"
        ports:
        - containerPort: 8080
        - containerPort: 3478
          protocol: UDP
        - containerPort: 10001  
          protocol: UDP
        - containerPort: 8443
        - containerPort: 1900
          protocol: UDP
        - containerPort: 8843
        - containerPort: 8880
        - containerPort: 6789
        - containerPort: 5514
          protocol: UDP
        volumeMounts:
        - name: unifi-storage
          mountPath: /config
      volumes:
      - name: unifi-storage
        persistentVolumeClaim:
          claimName: unifi-storage
      securityContext:
          runAsUser: 0
          runAsGroup: 0
          
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
spec:
  selector:
    app: unifi
  type: LoadBalancer
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      #targetPort: 8080
    - name: udp-3478
      protocol: UDP
      port: 3478
      #targetPort: 3478
    - name: udp-10001
      protocol: UDP
      port: 10001
      #targetPort: 10001
    - name: tcp-8443
      protocol: TCP
      port: 8443
      #targetPort: 8443
    - name: udp-1900
      protocol: UDP
      port: 1900
     # targetPort: 1900
    - name: tcp-8843
      protocol: TCP
      port: 8843
      #targetPort: 8843
    - name: tcp-8880
      protocol: TCP
      port: 8880
      #targetPort: 8880
    - name: tcp-6789
      protocol: TCP
      port: 6789
      #targetPort: 6789
    - name: udp-5514
      protocol: UDP
      port: 5514
      #targetPort: 5514
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-db
  namespace: unifi
spec:
  selector:
    app: unifi-db
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017 