apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: unifi-db-creds
  namespace: unifi
spec:
  vaultAuthRef: unifi-secrets-auth
  type: kv-v2
  mount: k8s
  path: unifi/mongocreds
  refreshAfter: 10s
  destination:
    name: unifi-mongo-creds
    create: true
  rolloutRestartTargets:
  - kind: Deployment
    name: unifi
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: unifi-secrets-auth
  namespace: unifi
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: unifi-mongo-creads-read
    serviceAccount: default
    #tokenExpirationSeconds: 600
    audiences: 
      - vault