apiVersion: core/v1
kind: PersistentVolumeClaim
metadata:
  name: unifidb-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-storage
  namespace: unifi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
  storageClassName: nfs-server