alertmanager:
  alertmanagerspec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-server
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
prometheus:
  prometheusspec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-server
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
grafana:
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    storageClassName: nfs-server
    accessModes:
      - ReadWriteOnce
    size: 10Gi