apiVersion: v1
kind: Service
metadata:
  name: unifi-os-server-webui-svc
  namespace: unifi
spec:
  type: LoadBalancer
  ports:
  - name: webui
    port: 443
    protocol: TCP
    targetPort: 443
  - name: rtp
    port: 5005
    protocol: TCP
    targetPort: 5005
  - name: id-hub
    port: 9543
    protocol: TCP
    targetPort: 9543  
  - name: mobile-speedtest
    port: 6789
    protocol: TCP
    targetPort: 6789
  - name: communication
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: network-app
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: hotspot-secured
    port: 8444
    protocol: TCP
    targetPort: 8444
  - name: syslog
    port: 5514
    protocol: UDP
    targetPort: 5514
  - name: discovery
    port: 10003
    protocol: UDP
    targetPort: 10003
  - name: site-supervisor
    port: 11084
    protocol: TCP
    targetPort: 11084
  - name: aqmps
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: hotspot-redirect-0
    port: 8880
    protocol: TCP
    targetPort: 8880
  - name: hotspot-redirect-1
    port: 8881
    protocol: TCP
    targetPort: 8881
  - name: hotspot-redirect-2
    port: 8882
    protocol: TCP
    targetPort: 8882
  
  selector:
    app: unifi-os-server

